"""
Report Generation and Export Service.
"""

from typing import Dict, Any, List
import io
import pandas as pd

def generate_csv_export(df: pd.DataFrame) -> bytes:
    """Export DataFrame to CSV bytes for download."""
    return df.to_csv(index=False).encode('utf-8')

def generate_html_report(
    dataset_name: str,
    profiling: Dict[str, Any],
    kpis: List[Dict[str, Any]],
    insights: Dict[str, str],
    quality_score: int
) -> str:
    """
    Generate an executive HTML report suitable for browser preview or PDF printing.
    """
    kpi_html = "".join([
        f"""
        <div style="background:#f8fafc; border:1px solid #e2e8f0; border-radius:8px; padding:16px; flex:1; min-width:180px;">
            <div style="color:#64748b; font-size:12px; text-transform:uppercase; font-weight:600;">{k['title']}</div>
            <div style="font-size:24px; font-weight:700; color:#0f172a; margin-top:4px;">{k.get('formatted_total', k.get('total'))}</div>
            <div style="font-size:12px; color:#64748b; margin-top:2px;">Avg: {k.get('formatted_average', k.get('average'))}</div>
        </div>
        """ for k in kpis
    ])
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>Executive Analysis Report - {dataset_name}</title>
        <style>
            body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; line-height: 1.6; color: #1e293b; max-width: 960px; margin: 40px auto; padding: 0 20px; }}
            h1 {{ color: #0f172a; border-bottom: 2px solid #2563eb; padding-bottom: 12px; margin-bottom: 8px; }}
            h2 {{ color: #1e293b; margin-top: 32px; border-bottom: 1px solid #e2e8f0; padding-bottom: 8px; }}
            .badge {{ display: inline-block; padding: 4px 10px; border-radius: 9999px; background: #e0e7ff; color: #3730a3; font-weight: 600; font-size: 13px; }}
            .kpi-container {{ display: flex; gap: 16px; flex-wrap: wrap; margin: 24px 0; }}
            .section-box {{ background: #ffffff; border: 1px solid #e2e8f0; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }}
            .score-circle {{ font-size: 36px; font-weight: 800; color: #16a34a; }}
        </style>
    </head>
    <body>
        <h1>GenAI Data Analyst Executive Report</h1>
        <p style="color:#64748b; margin-top:-4px;">Dataset: <strong>{dataset_name}</strong> | Generated: Built-in GenAI Engine</p>
        
        <div style="display:flex; justify-content:space-between; align-items:center; background:#f1f5f9; padding:16px 20px; border-radius:8px; margin: 20px 0;">
            <div>
                <strong>Dataset Overview:</strong> {profiling.get('shape', {}).get('rows', 0):,} records, {profiling.get('shape', {}).get('columns', 0)} columns
            </div>
            <div>
                Data Quality Score: <span class="badge" style="background:#dcfce7; color:#15803d; font-size:15px;">{quality_score} / 100</span>
            </div>
        </div>

        <h2>Core Key Performance Indicators</h2>
        <div class="kpi-container">
            {kpi_html}
        </div>

        <h2>Executive Summary</h2>
        <div class="section-box">
            {insights.get('executive_summary', 'No summary available.')}
        </div>

        <h2>Key Growth Trends</h2>
        <div class="section-box">
            {insights.get('key_trends', 'No trend insights available.')}
        </div>

        <h2>Anomalies & Operational Risks</h2>
        <div class="section-box">
            <strong>Anomalies:</strong> {insights.get('anomalies', 'No anomalies reported.')}<br><br>
            <strong>Identified Risks:</strong> {insights.get('risks', 'Standard monitoring recommended.')}
        </div>

        <h2>Strategic Recommendations</h2>
        <div class="section-box">
            {insights.get('recommendations', 'Continue tracking primary KPIs.')}
        </div>

        <footer style="margin-top:50px; text-align:center; color:#94a3b8; font-size:13px; border-top:1px solid #e2e8f0; padding-top:20px;">
            Report generated by GenAI Data Analyst Assistant &copy; 2025
        </footer>
    </body>
    </html>
    """
    return html
